# Generated by Django 5.1.1 on 2024-10-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='close_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='open_time',
            field=models.TimeField(),
        ),
    ]
