import type { Config } from "tailwindcss";
import daisyui from "daisyui";
import { light } from "@mui/material/styles/createPalette";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        lightBlue: '#D1E9F6',
        lightBlue2: '#D7ECF6',
        lightBlue3: '#D4DBF8',
        lightPurple1: '#F7DBF0',
        lightPurple2: '#F4EEFF',
        lightPurple3: '#AB95D6',
        lightPurple4: '#F6EBF4',
        lightPurple5: '#D2C2EF',
        lightSky: '#BFECFF',
        lightYellow: '#FFF8C9',
        lightPink: '#D1AFC2',
        lightPink2: "#ffddea",
        lightPink3: "#ffeaf2",
        lightPink4: "#fabcd4",
        darkGrey1: '#27374D',
        darkGrey2: '#526D82',
        lightGrey1: '#9DB2BF',
        lightGrey2: '#DDE6ED',
        darkPurple: '#424874',
        darkPurple2: '#704BAB',
        cream: '#FAF0E2',
        cream2: '#FEF9F2',
        cream3: '#FFF1E7',
        cream4: "#fffdf8",
        brightPink: '#C869B3',
        brightPink2: '#DD98D6',
        lightOrange1: '#FFBFB6',
        lightOrange2: '#FFD5B6',
        lightOrange3: '#FFE8E2',
        darkBlue: '#5a6194',
        lightBlue4: '#9fa2d4',
        lightPurple: '#9d70b4',
        lightPurple6: '#ebeaf6',
        lightPurple7: '#cb86dd',
        lightPurple8: '#e4d4f6',
        lightGreen: "#e2fedc",
        lightGreen2: "#96cbd0",
        lightGreen3: "#aad9a0",
        lightGreen4: "#7eda8f",
        lightGreen5: "#effaed",
        darkPink: "#f75ca2",
        hotPink: "#f376a5",
        darkGreen: "#789e84",
        green: "#e3ffdd",
        green2: "#b6ecaa",
        green3: "#7eda8f",
        brightPink: '#FFC4DD',
        brightPink1: '#E4AEC5',
        darkGreen: '#295939',
        darkGreen1: '#82A284',
      },
      height: {
        '26': '4rem',
        '42': '13rem',
        '60': '16rem',
        '76': '20rem',
        '80': '24rem',
        '83': '27rem',
        '100': '35rem',
        '110': '40rem',
        '120': '45rem',
        '122': '52rem',
      },
      width: {
        '32': '8rem',
        '34': '9rem',
        '70': '25rem',
        '90': '35rem',
        '100': '40rem',
        '122': '52rem',
        '42': '13rem',
      }
    },
  },
  plugins: [daisyui],
};
export default config;