[tool.pyink]
exclude = '''
# Exclude migrations and specific directories or files
migrations/
*/migrations/
settings.py  # Exclude specific files by name
tests/  # Exclude all files in the tests directory
static/
templates/
settings.py
env/
.venv/
venv/
**/site-packages/**
'''
