# Generated by Django 5.1.1 on 2024-10-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_business_close_time_alter_business_open_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="open_status",
            field=models.CharField(default="Closed", max_length=50),
        ),
    ]
