# Generated by Django 4.2.15 on 2024-10-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_business_open_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queue",
            name="business",
        ),
        migrations.RemoveField(
            model_name="queue",
            name="user",
        ),
        migrations.DeleteModel(
            name="Business",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Queue",
        ),
    ]
