import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/components/AuthProvider";
import SessionWrapper from "@/components/SessionWrapper";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Queue Management",
  description: "Generated by create next app",
};

const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-cream2 min-h-screen`}
      >
        <SessionWrapper>
          <AuthProvider>
            <div className="flex flex-wrap min-h-screen">
              <div className="flex-1">
                {children}
              </div>
            </div>
            <ToastContainer />
          </AuthProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}