# Generated by Django 5.1.2 on 2024-10-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_queue_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
