# Generated by Django 5.1 on 2024-11-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_queue', '0002_rename_alphabet_queue_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='close_time',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='business',
            name='open_time',
            field=models.TimeField(default='06:00'),
        ),
    ]
