# Generated by Django 5.1.3 on 2024-11-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_queue", "0003_business_close_time_business_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="image",
            field=models.ImageField(
                blank=True, default="profiles/default.png", upload_to="profiles/"
            ),
        ),
    ]
