# Generated by Django 5.1.3 on 2024-11-21 17:15

import my_queue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_queue", "0004_alter_business_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="image",
            field=models.ImageField(
                blank=True,
                default=my_queue.models.get_default_profile_image,
                upload_to="profiles/",
            ),
        ),
    ]
