name: Cypress E2E Tests

on:
  push:
    branches:
      - main
      - iteration8-test-front-new
  pull_request:
    branches:
      - main
      - iteration8-test-front-new


jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run Cypress E2E Tests
        run: |
          cd frontend
          npx cypress run
